### ISSUE TITLE
is there a way to map a shell script or a linux armv7 binary?

### ISSUE THREAD

**Issue by llbranco** [andrewfraley/magic_mapper#15]
I'm working on this project and i want to make things easier and more customizable to the final user
https://github.com/llbranco/PPLGPwn
https://github.com/zauceee/PPLGPwn

a demo video
https://www.youtube.com/watch?v=zYoesrUsIj8

thank you

**Comment by andrewfraley** [comment]
Hi @llbranco, you can just add a new function to either execute a string you supply as input, or hard code it to your specific command.  Check out the curl() function in the script for an example of running arbitrary commands.  

I never included this because it can be pretty fragile and from a security standpoint it's probably not the best idea, especially considering this has to run as root.
